export const NAVIGATE_TO_PAGE = 'NAVIGATE_TO_PAGE';

export const LOAD_PRODUCTS_REQUEST = 'LOAD_PRODUCTS_REQUEST';
export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS';

export const CHANGE_PRODUCT_TAG = 'CHANGE_PRODUCT_TAG';

export const LOAD_BY_TAGS_REQUEST = 'LOAD_BY_TAGS_REQUEST';
export const LOAD_BY_TAGS_SUCCESS = 'LOAD_BY_TAGS_SUCCESS';
export const LOAD_BY_TAGS_FAILURE = 'LOAD_BY_TAGS_FAILURE';

export const CHANGE_PURCHASE_QUANTITY = 'CHANGE_PURCHASE_QUANTITY';

export const ORDER = 'ORDER';
